// Code generated by mockery v2.5.1. DO NOT EDIT.

package policy

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockGitService is an autogenerated mock type for the GitService type
type MockGitService struct {
	mock.Mock
}

// ShallowClone provides a mock function with given fields: ctx, destination
func (_m *MockGitService) ShallowClone(ctx context.Context, destination string) error {
	ret := _m.Called(ctx, destination)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, destination)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Commit provides a mock function with given fields: ctx, rootPath, changesPath, msg
func (_m *MockGitService) Commit(ctx context.Context, rootPath string, changesPath string, msg string) error {
	ret := _m.Called(ctx, rootPath, changesPath, msg)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, rootPath, changesPath, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MasterPath provides a mock function with given fields:
func (_m *MockGitService) MasterPath() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
