# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

builds:
- binary: artifact
  id: artifact
  main: ./cmd/artifact/main.go
  goarch:
  - amd64
  goos:
  - darwin
  - linux
  env:
    - CGO_ENABLED=0
- binary: hamctl
  id: hamctl
  main: ./cmd/hamctl/main.go
  goarch:
  - amd64
  goos:
  - darwin
  - linux
  env:
    - CGO_ENABLED=0
- binary: server
  id: server
  main: ./cmd/server/main.go
  goarch:
  - amd64
  goos:
  - darwin
  - linux
  env:
    - CGO_ENABLED=0
- binary: daemon
  id: daemon
  main: ./cmd/daemon/main.go
  goarch:
  - amd64
  goos:
  - darwin
  - linux
  env:
    - CGO_ENABLED=0

dockers:
  - dockerfile: Dockerfile-server-goreleaser
    binaries:
    - server
    image_templates:
    - "quay.io/lunarway/release-manager:{{ .Tag }}"
    extra_files:
    - ssh_config
  - dockerfile: Dockerfile-daemon-goreleaser
    binaries:
    - daemon
    image_templates:
    - "quay.io/lunarway/release-daemon:{{ .Tag }}"

archives:
  - id: archives
    format: binary
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386


checksum:
  name_template: '{{ .ProjectName }}-checksums.txt'

snapshot:
  name_template: "git-{{.Commit}}"

release:
  name_template: "v{{.Version}}"
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
