version: 2

builds:
- binary: artifact
  id: artifact
  main: ./cmd/artifact/main.go
  goarch:
  - amd64
  - arm64
  goos:
  - darwin
  - linux
  env:
    - CGO_ENABLED=0
- binary: hamctl
  id: hamctl
  main: ./cmd/hamctl/main.go
  goarch:
  - amd64
  - arm64
  goos:
  - darwin
  - linux
  env:
    - CGO_ENABLED=0
- binary: server
  id: server
  main: ./cmd/server/main.go
  goarch:
  - amd64
  - arm64
  goos:
  - darwin
  - linux
  env:
    - CGO_ENABLED=0
- binary: daemon
  id: daemon
  main: ./cmd/daemon/main.go
  goarch:
  - amd64
  - arm64
  goos:
  - darwin
  - linux
  env:
    - CGO_ENABLED=0

dockers_v2:
  - id: release-manager
    dockerfile: Dockerfile-server-goreleaser
    ids:
    - server
    images:
    - "quay.io/lunarway/release-manager"
    tags:
    - "{{ .Tag }}"
    extra_files:
    - ssh_config
    platforms:
    - linux/amd64
    - linux/arm64
  - id: release-daemon
    dockerfile: Dockerfile-daemon-goreleaser
    ids:
    - daemon
    images:
    - "quay.io/lunarway/release-daemon"
    tags:
    - "{{ .Tag }}"
    platforms:
    - linux/amd64
    - linux/arm64

archives:
  - id: archives
    formats: [ 'binary' ]
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: '{{ .ProjectName }}-checksums.txt'

snapshot:
  version_template: "git-{{.Commit}}"

release:
  name_template: "v{{.Version}}"
  prerelease: auto

changelog:
  disable: true
