# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

builds:
- binary: artifact
  main: ./cmd/artifact/main.go
  goarch:
  - amd64    
  goos:
  - darwin
  - linux
- binary: hamctl
  main: ./cmd/hamctl/main.go
  goarch:
  - amd64    
  goos:
  - darwin
  - linux
- binary: server
  main: ./cmd/server/main.go
  goarch:
  - amd64
  goos:
  - darwin
  - linux
- binary: daemon
  main: ./cmd/daemon/main.go
  goarch:
  - amd64
  goos:
  - darwin
  - linux

checksum:
  name_template: '{{ .ProjectName }}-checksums.txt'

snapshot:
  name_template: "git-{{.Commit}}"

release:
  name_template: "v{{.Version}}"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'