version: 2

builds:
- binary: artifact
  id: artifact
  main: ./cmd/artifact/main.go
  goarch:
  - amd64
  goos:
  - darwin
  - linux
  env:
    - CGO_ENABLED=0
- binary: hamctl
  id: hamctl
  main: ./cmd/hamctl/main.go
  goarch:
  - amd64
  goos:
  - darwin
  - linux
  env:
    - CGO_ENABLED=0
- binary: server
  id: server
  main: ./cmd/server/main.go
  goarch:
  - amd64
  goos:
  - darwin
  - linux
  env:
    - CGO_ENABLED=0
- binary: daemon
  id: daemon
  main: ./cmd/daemon/main.go
  goarch:
  - amd64
  goos:
  - darwin
  - linux
  env:
    - CGO_ENABLED=0

dockers:
  - dockerfile: Dockerfile-server-goreleaser
    image_templates:
    - "quay.io/lunarway/release-manager:{{ .Tag }}"
    extra_files:
    - ssh_config
  - dockerfile: Dockerfile-daemon-goreleaser
    image_templates:
    - "quay.io/lunarway/release-daemon:{{ .Tag }}"

archives:
  - id: archives
    format: binary
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: '{{ .ProjectName }}-checksums.txt'

snapshot:
  version_template: "git-{{.Commit}}"

release:
  name_template: "v{{.Version}}"
  prerelease: auto

changelog:
  disable: true
