# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

builds:
- binary: artifact
  main: ./cmd/artifact/main.go
  goarch:
  - amd64    
  goos:
  - darwin
  - linux
- binary: hamctl
  main: ./cmd/hamctl/main.go
  goarch:
  - amd64    
  goos:
  - darwin
  - linux
- binary: server
  main: ./cmd/server/main.go
  goarch:
  - amd64
  goos:
  - darwin
  - linux
- binary: daemon
  main: ./cmd/daemon/main.go
  goarch:
  - amd64
  goos:
  - darwin
  - linux

dockers:
  - dockerfile: Dockerfile-server-goreleaser
    binaries:
    - server
    image_templates:
    - "quay.io/lunarway/release-manager:latest"
    - "quay.io/lunarway/release-manager:v{{ .Major }}"
    - "quay.io/lunarway/release-manager:v{{ .Major }}.{{ .Minor }}"
    - "quay.io/lunarway/release-manager:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    extra_files:
    - ssh_config
  - dockerfile: Dockerfile-daemon-goreleaser
    binaries:
    - daemon
    image_templates:
    - "quay.io/lunarway/release-daemon:latest"
    - "quay.io/lunarway/release-daemon:v{{ .Major }}"
    - "quay.io/lunarway/release-daemon:v{{ .Major }}.{{ .Minor }}"
    - "quay.io/lunarway/release-daemon:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}"

archive:
  format: binary
  name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"
  replacements:
    darwin: darwin
    linux: linux
    windows: windows
    386: i386

checksum:
  name_template: '{{ .ProjectName }}-checksums.txt'

snapshot:
  name_template: "git-{{.Commit}}"

release:
  name_template: "v{{.Version}}"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'