FROM golang:1.18.4 as builder
WORKDIR /app
ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=amd64

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY internal/ ./internal/
COPY cmd/daemon/ ./cmd/daemon/

RUN go build -o daemon cmd/daemon/main.go

FROM scratch
WORKDIR /app

COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /app/daemon .

ENTRYPOINT [ "./daemon", "start" ]
