FROM --platform=$BUILDPLATFORM alpine:3.24.0 AS builder

RUN apk update
RUN apk add ca-certificates

FROM scratch
ARG TARGETPLATFORM
ENTRYPOINT [ "/daemon", "start" ]
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY $TARGETPLATFORM/daemon /daemon
