FROM alpine:3.17.1 as builder

RUN apk update
RUN apk add ca-certificates

FROM scratch
ENTRYPOINT [ "/daemon", "start" ]
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY daemon /
