apiVersion: apps/v1
kind: Deployment
metadata:
  name: crashloopbackoff
  labels:
    app: crashloopbackoff
  annotations:
    kubernetes.io/change-cause: 'nginx:1.14.2'
    lunarway.com/author: 'kni@lunar.app'
    lunarway.com/artifact-id: 'master-1fdc8087ee-5d4da5aa89'
    lunarway.com/controlled-by-release-manager: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crashloopbackoff
  template:
    metadata:
      labels:
        app: crashloopbackoff
      annotations:
        kubernetes.io/change-cause: 'nginx:1.14.2'
        lunarway.com/author: 'kni@lunar.app'
        lunarway.com/artifact-id: 'master-1fdc8087ee-5d4da5aa89'
        lunarway.com/controlled-by-release-manager: 'true'
    spec:
      containers:
      - name: crashloopbackoff
        image: alpine
        command: [ 'sh' ]
        args: [ '-c', 'exit 666' ]