apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
  annotations:
    kubernetes.io/change-cause: 'nginx:1.14.2'
    lunarway.com/author: 'kni@lunar.app'
    lunarway.com/artifact-id: 'nginx:1.14.2'
    lunarway.com/controlled-by-release-manager: 'true'
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        kubernetes.io/change-cause: 'nginx:1.14.2'
        lunarway.com/author: 'kni@lunar.app'
        lunarway.com/artifact-id: 'nginx:1.14.2'
        lunarway.com/controlled-by-release-manager: 'true'
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80