apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
  annotations:
    kubernetes.io/change-cause: 'nginx:1.14.2'
    lunarway.com/author: 'kni@lunar.app'
    lunarway.com/artifact-id: 'master-1fdc8087ee-5d4da5aa89'
    lunarway.com/controlled-by-release-manager: 'true'
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80