apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
  annotations:
    kubernetes.io/change-cause: 'nginx-slim:0.7'
    lunarway.com/author: 'kni@lunar.app'
    lunarway.com/artifact-id: 'nginx-slim:0.7'
    lunarway.com/controlled-by-release-manager: 'true'
spec:
  selector:
    matchLabels:
      app: nginx # has to match .spec.template.metadata.labels
  serviceName: "nginx"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: nginx # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.7
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi