name: GoReleaser Check

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  goreleaser-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25.3
      - name: Run GoReleaser Check
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: check
